"""HTML report generation (self-contained, matplotlib figures embedded as PNG data URIs)."""

from __future__ import annotations

import base64
import io
from pathlib import Path

import numpy as np

_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{title}</title>
<style>
:root {{ color-scheme: light dark; --fg:#1a1a1a; --bg:#fff; --mut:#666; --line:#ddd; --accent:#1b6ec2; --warn:#b45309; --warnbg:#fef3c7; }}
@media (prefers-color-scheme: dark) {{ :root {{ --fg:#e8e8e8; --bg:#16181a; --mut:#9aa0a6; --line:#333; --accent:#63a4ff; --warn:#fbbf24; --warnbg:#3a2e0b; }} }}
body {{ font: 14px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif; color:var(--fg); background:var(--bg); margin:0; padding:28px 32px; }}
h1 {{ font-size:22px; margin:0 0 4px; }} h2 {{ font-size:16px; margin:28px 0 8px; border-bottom:1px solid var(--line); padding-bottom:4px; }}
.sub {{ color:var(--mut); margin-bottom:18px; }}
table {{ border-collapse:collapse; width:100%; margin:8px 0 4px; font-size:13px; }}
th,td {{ text-align:right; padding:5px 8px; border-bottom:1px solid var(--line); white-space:nowrap; }}
th:first-child,td:first-child,th.l,td.l {{ text-align:left; }}
th {{ color:var(--mut); font-weight:600; }}
tr.main td {{ font-weight:600; }}
.warn {{ background:var(--warnbg); color:var(--warn); border-left:3px solid var(--warn); padding:9px 12px; margin:8px 0; border-radius:3px; }}
.kv {{ display:flex; flex-wrap:wrap; gap:22px; margin:6px 0 14px; }}
.kv div {{ min-width:120px; }} .kv b {{ display:block; color:var(--mut); font-weight:600; font-size:12px; }}
img {{ max-width:100%; height:auto; margin:6px 0; }}
.scroll {{ overflow-x:auto; }}
footer {{ color:var(--mut); font-size:12px; margin-top:32px; border-top:1px solid var(--line); padding-top:10px; }}
</style></head><body>
<h1>{title}</h1>
<div class="sub">{subtitle}</div>
{body}
<footer>Generated by lcmsdeconv {version}. Masses are average masses unless marked mono.</footer>
</body></html>
"""


def _fig_to_uri(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight")
    import matplotlib.pyplot as plt

    plt.close(fig)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def _table(headers, rows, row_classes=None) -> str:
    left = ' class="l"'
    th = "".join("<th" + (left if i == 0 else "") + ">" + str(h) + "</th>"
                 for i, h in enumerate(headers))
    trs = []
    for i, r in enumerate(rows):
        cls = ' class="' + row_classes[i] + '"' if row_classes and row_classes[i] else ""
        tds = "".join("<td" + (left if j == 0 else "") + ">" + str(c) + "</td>"
                      for j, c in enumerate(r))
        trs.append("<tr" + cls + ">" + tds + "</tr>")
    body = "".join(trs)
    return ('<div class="scroll"><table><thead><tr>' + th
            + "</tr></thead><tbody>" + body + "</tbody></table></div>")


def _fmt(v, nd=3):
    if v is None:
        return "-"
    if isinstance(v, float):
        if v != v:
            return "-"
        return f"{v:,.{nd}f}"
    return str(v)


def build_report(result, path: str | Path, title: str | None = None, plots: bool = True) -> Path:
    from .. import __version__

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    parts: list[str] = []

    m = result.method
    parts.append('<div class="kv">'
                 f'<div><b>Run</b>{result.run_name}</div>'
                 f'<div><b>Method</b>{m.name}</div>'
                 f'<div><b>Instrument</b>{m.instrument.kind.upper()} R={m.instrument.resolution:,.0f}</div>'
                 f'<div><b>Species found</b>{len(result.species)}</div>'
                 f'<div><b>Regions</b>{len(result.regions)}</div>'
                 f'<div><b>Processing</b>{result.timings.get("total_s", 0):.1f} s</div>'
                 "</div>")

    for w in result.warnings:
        parts.append(f'<div class="warn"><b>Warning.</b> {w}</div>')
    if result.saturation and result.saturation.peak_flags:
        for pid, flags in result.saturation.peak_flags.items():
            parts.append(f'<div class="warn"><b>Peak {pid}.</b> {"; ".join(flags)}</div>')

    if plots:
        parts.append("<h2>Chromatograms</h2>")
        parts.append(_plot_chromatograms(result))

    # peak tables
    for name, table in result.peak_tables.items():
        if not len(table) or name.startswith("m "):
            continue
        parts.append(f"<h2>Peak table: {name}</h2>")
        rows = [[p.id, _fmt(p.rt, 3), _fmt(p.start, 3), _fmt(p.end, 3), _fmt(p.area, 1),
                 _fmt(p.height, 1), _fmt(p.width_half, 4), _fmt(p.area_pct, 3),
                 _fmt(p.tailing, 2), p.code] for p in table.peaks]
        parts.append(_table(["#", "RT (min)", "Start", "End", f"Area ({table.area_unit})",
                             "Height", "Width 50%", "Area %", "Tailing", "Code"], rows))

    # species / impurities
    if result.impurities:
        parts.append("<h2>Deconvolved species and impurities</h2>")
        rows, classes = [], []
        for r in result.impurities:
            adducts = ", ".join(f"{k} {v*100:.1f}%" for k, v in
                                sorted(r["adducts"].items(), key=lambda x: -x[1])[:4])
            rows.append([r["name"] or "-", _fmt(r["mass"], 2), _fmt(r["delta_vs_main"], 3),
                         _fmt(r["rt"], 3), _fmt(r["area"], 1), _fmt(r["percent"], 4),
                         r["charges"], _fmt(r["mass_spread_ppm"], 1), adducts or "-",
                         r["annotation"]])
            classes.append("main" if "main component" in r["annotation"] else "")
        parts.append(_table(["Species", "Mass (Da)", "Δ vs main", "RT (min)", "Area", "% of ions",
                             "Charges", "Spread (ppm)", "Adducts", "Annotation"], rows, classes))

    if result.purity:
        parts.append("<h2>Purity</h2>")
        pur = result.purity
        rows = [[r["id"], _fmt(r["rt"], 3), _fmt(r["area"], 1), _fmt(r["area_pct"], 3), r["code"],
                 "main" if r["is_main"] else ""] for r in pur.get("rows", [])]
        parts.append(_table(["#", "RT (min)", "Area", "Area %", "Code", ""], rows))
        ms = pur.get("ms") or {}
        if ms:
            parts.append(f'<div class="kv"><div><b>MS purity (main species)</b>'
                         f'{ms.get("main_percent", 0):.3f} %</div>'
                         f'<div><b>Main mass</b>{_fmt(ms.get("main_mass"), 2)} Da</div>'
                         f'<div><b>Species counted</b>{ms.get("n_species", 0)}</div></div>')

    if result.potency:
        parts.append("<h2>Potency</h2>")
        po = result.potency
        cal = po.get("calibration", {})
        parts.append('<div class="kv">'
                     f'<div><b>Area</b>{_fmt(po.get("area"), 1)}</div>'
                     f'<div><b>Amount</b>{_fmt(po.get("amount"), 4)} {po.get("unit", "")}</div>'
                     f'<div><b>% of nominal</b>{_fmt(po.get("percent_of_nominal"), 2)}</div>'
                     f'<div><b>Calibration</b>{cal.get("mode", "-")} r²={_fmt(cal.get("r_squared"), 5)}</div>'
                     "</div>")

    if plots and result.species:
        parts.append("<h2>Deconvolved ion chromatograms</h2>")
        parts.append(_plot_species(result))

    html = _TEMPLATE.format(
        title=title or f"LC-MS deconvolution report: {result.run_name}",
        subtitle=f"Method {m.name} &middot; {m.description}" if m.description else f"Method {m.name}",
        body="\n".join(parts), version=__version__,
    )
    path.write_text(html, encoding="utf-8")
    return path


def _plot_chromatograms(result) -> str:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    chroms = [(k, v) for k, v in result.chromatograms.items() if v.kind in ("tic", "uv", "bpc")]
    if not chroms:
        return ""
    fig, axes = plt.subplots(len(chroms), 1, figsize=(9, 2.3 * len(chroms)), sharex=True, squeeze=False)
    for ax, (name, ch) in zip(axes[:, 0], chroms):
        ax.plot(ch.time, ch.intensity, lw=0.9, color="#1b6ec2")
        table = result.peak_tables.get(name)
        if table:
            for p in table.peaks:
                m = (ch.time >= p.start) & (ch.time <= p.end)
                if m.sum() > 1:
                    base = np.linspace(p.baseline_start, p.baseline_end, int(m.sum()))
                    ax.fill_between(ch.time[m], base, ch.intensity[m], alpha=0.18, color="#1b6ec2")
                    ax.plot([p.start, p.end], [p.baseline_start, p.baseline_end], lw=0.8, color="#b45309")
                    ax.annotate(f"{p.rt:.2f}", (p.rt, p.height + p.baseline_start),
                                fontsize=7, ha="center", va="bottom")
        ax.set_ylabel(name, fontsize=9)
        ax.tick_params(labelsize=8)
    axes[-1, 0].set_xlabel("Retention time (min)", fontsize=9)
    return f'<img src="{_fig_to_uri(fig)}" alt="chromatograms">'


def _plot_species(result) -> str:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    n = min(len(result.species), result.method.report.max_species_plots)
    if n == 0:
        return ""
    fig, ax = plt.subplots(figsize=(9, 3.4))
    for s in result.species[:n]:
        ax.plot(s.time, s.intensity, lw=1.0, label=f"{s.mass:,.1f} Da ({s.name or ''})")
    ax.set_xlabel("Retention time (min)", fontsize=9)
    ax.set_ylabel("Deconvolved intensity", fontsize=9)
    ax.tick_params(labelsize=8)
    ax.legend(fontsize=7, ncol=2, frameon=False)
    img = f'<img src="{_fig_to_uri(fig)}" alt="deconvolved EICs">'

    masses = np.array([s.mass for s in result.species])
    inten = np.array([s.total_intensity for s in result.species])
    fig2, ax2 = plt.subplots(figsize=(9, 2.8))
    if masses.size:
        ax2.vlines(masses, 0, inten, color="#1b6ec2", lw=1.4)
        ax2.set_xlabel("Neutral mass (Da)", fontsize=9)
        ax2.set_ylabel("Summed intensity", fontsize=9)
        ax2.tick_params(labelsize=8)
        top = result.species[0]
        ax2.annotate(f"{top.mass:,.1f}", (top.mass, top.total_intensity), fontsize=8,
                     ha="center", va="bottom")
    return img + f'<img src="{_fig_to_uri(fig2)}" alt="deconvolved mass spectrum">'
